Repository lakejason0/mediawiki-skins-Lakeus, pull requests merged in 2024-01, with the labels that each got.

#22 #22 | doc: Fix capitalization in README.md
  README.md
Labels: documentation

#23 Rename LakeusHooks
  includes/LakeusHooks.php
  skin.json
Labels: enhancement

#24 #24 | Convert to the new hook system
  includes/LakeusHooks.php
  skin.json
Labels: deprecation

#25 #25 | Reorder skin.json
  skin.json
Labels: enhancement

#26 #26 | Remove unneeded wp prefix from hide-if
  includes/LakeusHooks.php
Labels: enhancement

#27 #27 | Revert "Rename LakeusHooks"
  includes/Hooks.php
  skin.json
Labels: enhancement

#29 #29 | doc: Add documentations
  CODE_OF_CONDUCT.md
  HISTORY.md
  RELEASE-NOTES-1.1.md
  SECURITY.md
Labels: documentation

#30 #30 | Fix "Localisation updates from https://translatewiki.net."
  RELEASE-NOTES-1.1.md
  i18n/tw.json
  i18n/yue-hant.json
Labels: i18n

#33 #33 | Migrate templateDirectory option to skin.json
  RELEASE-NOTES-1.1.md
  includes/SkinLakeus.php
  skin.json
Labels: deprecation

#32 #32 | Fix "access to private variable of parent class" in SkinLakeus.php
  RELEASE-NOTES-1.1.md
  includes/SkinLakeus.php
  skin.json
Labels: bug

#35 #35 | Unify indentation for en.json
  RELEASE-NOTES-1.1.md
  i18n/en.json
Labels: i18n
